import mongoose, { Schema, model } from "mongoose";

const donationSchema = new Schema({
    donor: {
        type: Schema.Types.ObjectId,
        ref: "User", 
        required: [true, "A donation must belong to a user"]
    },
    campaign: {
        type: Schema.Types.ObjectId,
        ref: "campaign", // Links to your campaignModel
        required: [true, "A donation must be linked to a campaign"]
    },
    amount: {
        type: Number,
        required: [true, "Donation amount is required"],
        min: [1, "Minimum donation is 1 unit"]
    },
    paymentStatus: {
        type: String,
        enum: ["pending", "success", "failed"],
        default: "pending"
    },
    transactionId: {
        type: String,   //to confirm payment through uiq generated by gateway
        required: true,
        unique: true
    },
    description: {
        type: String,
        trim: true,
        maxLength: [200, "Message cannot exceed 200 characters"]
    }
}, {
    timestamps: true,
    versionKey: false
});

export const donationModel = mongoose.models.Donation || model("Donation", donationSchema);